FMS/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FMS.BL;
using FMS.BL.Buisness;
using FMS.BL.Utilities;

namespace FMS.Controllers
{
    public class DocumentController : Controller
    {
        // GET: Document
        public ActionResult Documents(long? DocumentsId)
        {
            ViewBag.ParentMenu = "administrator";
            ViewBag.ChildMenu = "document";
            Documents documents = new Documents();
            DocumentBuisness documentBuisness = null;
            try
            {
                documentBuisness = new DocumentBuisness();
                if(DocumentsId>0)
                {
                    documents = documentBuisness.GetDocuments(DocumentsId, 11).SingleOrDefault();
                }
              

            }
            catch(Exception ex)
            {
                AppLogger.Instance.Error(this.GetType(), "Unable to  document page", ex, "Documents");

            }
            return View(documents);
        }
        [HttpPost]
        public ActionResult Documents(HttpPostedFileBase postedFile, Documents documents)
        {
            ViewBag.ParentMenu = "administrator";
            ViewBag.ChildMenu = "document";
            DocumentBuisness documentBuisness = null;
            Status status = null;
            try
            {
                if (ModelState.IsValid)
                {
                    documentBuisness = new DocumentBuisness();
                    status = new Status();
                    long userid = 11;
                    string path = Server.MapPath("~/Uploads/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    postedFile.SaveAs(path + Path.GetFileName(postedFile.FileName));
                    documents.DocumentPath = "/Uploads/" + postedFile.FileName;
                    status = documentBuisness.AddUpdateDocument(documents, userid);
                    TempData["SuccessFlag"] = status.SuccessFlag;
                    TempData["Msg"] = status.Msg;
                    if (status.SuccessFlag == "1")
                    {
                        return RedirectToAction("List");
                    }
                    else
                    {
                        return View(documents);
                    }
                }
                
            }
            catch (Exception ex)
            {
                AppLogger.Instance.Error(this.GetType(), "Unable to add document", ex, "Documents");
            }


            return View(documents);
        }

        public ActionResult List()
        {
            ViewBag.ParentMenu = "administrator";
            ViewBag.ChildMenu = "document";
            Documents dc = new Documents();
            return View(dc);
        }

        [HttpPost]
        public JsonResult LoadDocuments(int DocumentsId)
        {
            ViewBag.ParentMenu = "administrator";
            ViewBag.ChildMenu = "document";
            long userid = 11;
            List<Documents> documents = null;
            DocumentBuisness documentBuisness = null;
            try
            {
                documents = new List<Documents>();
                documentBuisness = new DocumentBuisness();
                documents = documentBuisness.GetDocuments(DocumentsId, userid).Where(i => i.IsDeleted == false).ToList();
            }
            catch (Exception ex)
            {
                AppLogger.Instance.Error(this.GetType(), "Unable to fetch documents list", ex, "LoadDocuments");
            }

            return Json(documents, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Delete(int DocumentsId)
        {
            ViewBag.ParentMenu = "administrator";
            ViewBag.ChildMenu = "document";
            DocumentBuisness documentBuisness = null;
            Documents documents = null;
            Status status = null;
            long userid = 11;
            try
            {
                documentBuisness = new DocumentBuisness();
                documents = new Documents();
                status = new Status();
                documents = documentBuisness.GetDocuments(DocumentsId, userid).SingleOrDefault();
                 var fullPath = Server.MapPath(documents.DocumentPath);
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
                status = documentBuisness.DeleteDocument(DocumentsId, userid);
                TempData["SuccessFlag"] = status.SuccessFlag;
                TempData["Msg"] = status.Msg;

            }
            catch (Exception ex)
            {
                AppLogger.Instance.Error(this.GetType(), "Unable to delete Item ", ex, "Delete");
            }
            return RedirectToAction("List");
        }


    }
}

FMS/Views/Document/Documents.cshtml
@model FMS.BL.Documents
@{
    ViewBag.Title = "Documents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Documents</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/home/index">Master</a></li>
                        <li class="breadcrumb-item active">Documents</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">




            @using (Html.BeginForm("Documents", "Document", FormMethod.Post, new { enctype = "multipart/form-data", id = "Add" }))
            {
                <div class="row">
                    <div class="col-md-12">
                        <!-- general form elements disabled -->
                        <div class="card card-warning">

                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <!-- text input -->
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.DocumentName)<span class="text-red">*</span>
                                            @Html.HiddenFor(model => model.DocumentId)
                                            @Html.EditorFor(model => model.DocumentName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Document Name" } })
                                            @Html.ValidationMessageFor(model => model.DocumentName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>



                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label for="exampleInputFile">File input</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file" class="custom-file-input" name="postedFile" id="exampleInputFile">
                                                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                                </div>
                                                
                                            </div>
                                        </div>


                                        @*<div class="form-group">
                                            <span>Select File:</span>
                                            <input type="file" name="postedFile" />
                                            <hr />
                                        </div>*@
                                    </div>

                                </div>

                                <button onclick="Reset()" type="button" class="btn btn-secondary text-left">Reset</button>
                                <button type="submit" form="Add" class="btn btn-primary btn-left">Submit</button>
                            </div>
                        </div>

                    </div>

                    @*<input type="submit" value="Upload" />*@
                </div>
            }

            <!-- /.card-body -->
            <!-- /.card -->
            <!-- general form elements disabled -->
            <!-- /.card -->

        </div>

    </section>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        bsCustomFileInput.init();
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {

        if ('@TempData["SuccessFlag"]' == "1") {
            toastr.success('@TempData["Msg"]');
        }
        else if ('@TempData["SuccessFlag"]' == "0") {
            toastr.error('@TempData["Msg"]');
        }
    });
</script>

FMS/Views/Document/List.cshtml
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Document list </h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/home/index">Master</a></li>
                        <li class="breadcrumb-item active">Document list</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-12">

                    <!-- general form elements disabled -->
                    <div class="card card-warning">

                        <!-- /.card-header -->
                        <div class="card-body">
                            @*  <button onclick="Add();" type="button" class="btn  bg-gradient-primary"><i class="fas fa-plus"></i>Add Employe</button>*@
                            @*// @Html.ActionLink("Add Employee", "Add", new { @class = "btn  bg-gradient-primary" })*@
                            @Html.ActionLink("Add Document", "Documents", "Document",
                            new { @class = "btn  bg-gradient-primary" })
                            <div class="clearfix"></div><br />
                            <div id="tblDocuments">

                            </div>
                        </div>

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
                <!-- general form elements disabled -->
                <!-- /.card -->
            </div>

        </div>

    </section>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        if ('@TempData["SuccessFlag"]' == "1") {
            toastr.success('@TempData["Msg"]');
        }
        else if ('@TempData["SuccessFlag"]' == "0") {
            toastr.error('@TempData["Msg"]');
        }
    });


$(function () {
    LoadDocuments(0);
});

    function LoadDocuments(DocumentsId) {

    var requestData = {
        DocumentsId: DocumentsId
    };
    $.ajax({
        url: '/Document/LoadDocuments',
        type: 'POST',
        data: JSON.stringify(requestData),
        dataType: 'json',
        contentType: 'application/json; charset=utf-8',
        async: true,
        processData: true,
        cache: false,
        error: function (xhr) {
            alert('Error: ' + xhr.statusText);
        },
            success: function (result) {

               
                $('#tblDocuments').html("");
                var tblHead = '<table class="table table-bordered table-striped" id="example1" cellspacing="0" cellpadding="4" align="Center" style="color:#333333;border-collapse:collapse;"><thead><tr style="color:White;background-color:#1C5E55;font-weight:bold;"><th scope="col">Document Name</th><th scope="col">Action</th></tr></thead><tbody>';
                //alert(tblHead);
                var tbody = ""
                for (var i = 0; i < result.length; i++) {
                    
                    //  tbody = tbody + '<tbody><tr><td align="left" id=id_' + result[i].roleTitle + '>' + result[i].roleTitle + '</td><td id=id_' + result[i].Permissions + '>' + result[i].Permissions + '</td><td class="td-actions text-center"><a href="#" class="" id="btnCreateRole" onclick="EditRole(\'' + result[i].roleID + '\');"><i class="far fa-edit text-warning"></i> </a>&nbsp;<a href="#" class="" id="btnCreateRole" onclick="DeleteRole(\'' + result[i].roleID + '\')"><i class="fas fa-times text-danger"></i> </a></td></tr>';
                    tbody = tbody + '<tr style="background-color:White;"><td>' + result[i].DocumentName + '</td ><td><a href="' + result[i].DocumentPath + '" download><i class="fas fa-download"></i></a >&nbsp;&nbsp;<a href="#" onclick="Delete(' + result[i].DocumentId + ')"><i class="far fa-trash-alt"></i></i></a >&nbsp;&nbsp;<a href="#" onclick="Edit(' + result[i].DocumentId + ');"><i class="fa fa-fw fa-edit" ></i></a ></td></tr >'
                }
                $('#tblDocuments').html(tblHead + tbody + '</tbody></table>');
                $("#example1").DataTable();
            },
        });
    }

    function Edit(DocumentsId) {
        window.location.href = '/Document/Documents?DocumentsId=' + DocumentsId + '';
    }

    function Delete(DocumentsId) {
       // alert('/Document/Delete?DocumentsId=' + DocumentsId + ')
        bootbox.confirm("Are you sure you want to delete this document?", function (confirm) {
            if (confirm == true) {
                window.location.href = '/Document/Delete?DocumentsId=' + DocumentsId + '';
                // LoadEmployee(0);
            }


        })
    }
</script>