FMS/Controllers/UserController.cs
using FMS.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FMS.BL.Buisness;
using FMS.BL.Utilities;


namespace FMS.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult List()
        {
            return View();
        }
        // ADD: User
        public ActionResult Add(int? id)
        {
        
            UserBuisness userBuisness = null;
            
            User user = null;
            RoleBuisness roleBuisness = null;
            List<Role> roles = null;
            long userid = 11;

            try
            {
                userBuisness = new UserBuisness();
                user = new User();
                user.IsActive = true;
                roleBuisness = new RoleBuisness();
                roles = new List<Role>();
                roles = roleBuisness.GetRole(0, 11).Where(i => i.IsActive == true && i.IsDeleted == false).ToList();
                ViewBag.ForRole = new SelectList(roles, "RoleId", "Name", 0);
                if (id > 0)
                {
                    user = userBuisness.GetAlluser(id, userid).SingleOrDefault();
                }
            }
            catch (Exception ex)
            {
                AppLogger.Instance.Error(this.GetType(), "Unable to render Employee Add page", ex, "Add");
            }
            return View(user);
        }

        // ADD: Employee : POST
        [HttpPost]
        public ActionResult Add(User user)
        {
            List<User> users = null;
            UserBuisness userBuisness = null;
            Status status = null;
            RoleBuisness roleBuisness = null;
            List<Role> roles = null;
            try
            {
                userBuisness = new UserBuisness();
                users = new List<User>();
                status = new Status();
                roleBuisness = new RoleBuisness();
                roles = new List<Role>();
                roles = roleBuisness.GetRole(0, 11).Where(i => i.IsActive == true && i.IsDeleted == false).ToList();
                ViewBag.ForRole = new SelectList(roles, "RoleId", "Name", 0);

                user.CompanyId = 12;
                //// string uid = Session["UserBE"].UserId;
                long userid = 11;
                var errors = ModelState.Values.SelectMany(v => v.Errors);
                if (ModelState.IsValid)
                {
                    user.Password = BL.Utilities.Common.Encrypt(user.Password);
                    status = userBuisness.AddUpdateuser(user, userid);
                    // ViewBag.Status = status;
                    TempData["SuccessFlag"] = status.SuccessFlag;
                    TempData["Msg"] = status.Msg;
                    if (status.SuccessFlag == "1")
                    {
                        return RedirectToAction("List");
                    }
                    else
                    {
                        return View(user);

                    }

                }
                else
                {
                    return View(user);
                }

            }
            catch (Exception ex)
            {
                AppLogger.Instance.Error(this.GetType(), "Unable to post user Add page", ex, "Add");
                return View(user);
            }

        }

        [HttpPost]
        public JsonResult LoadUser(int id)
        {
            //// string uid = Session["UserBE"].UserId;
            long userid = 11;
            List<User> users = null;
            UserBuisness userBuisness = null;

            try
            {
                users = new List<User>();
                userBuisness = new UserBuisness();
                // AppLogger.Instance.Info(this.GetType(), "Fetch the list of all category", "LoadCategory");aa
                users = userBuisness.GetAlluser(id, userid).Where(i => i.IsDeleted == false).ToList();
            }
            catch (Exception ex)
            {
                AppLogger.Instance.Error(this.GetType(), "Unable to fetch user list", ex, "LoadUser");
            }

            return Json(users, JsonRequestBehavior.AllowGet);
        }
       
        public ActionResult Delete(int userid)
        {
            UserBuisness userBuisness = null;
            Status status = null;
            long Userid = 11;
            try
            {
                userBuisness = new UserBuisness();
                status = new Status();
                status = userBuisness.Deleteuser(userid, Userid);
                TempData["SuccessFlag"] = status.SuccessFlag;
                TempData["Msg"] = status.Msg;

            }
            catch (Exception ex)
            {
                AppLogger.Instance.Error(this.GetType(), "Unable to delete user ", ex, "Delete");
            }
            return RedirectToAction("List");
        }

    }
}

FMS/Views/User/Add.cshtml
@model FMS.BL.User
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Add User </h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/Home/Index">Administrator</a></li>
                        <li class="breadcrumb-item"><a href="/User/List">User</a></li>
                        <li class="breadcrumb-item active">Add User</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">
            @using (Html.BeginForm("Add", "User", FormMethod.Post, new { id = "Add" }))
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-md-12">
                        <!-- general form elements disabled -->
                        <div class="card card-warning">

                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <!-- text input -->
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.FullName)<span class="text-red">*</span>
                                            @Html.HiddenFor(model => model.Id)
                                            @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Full Name" } })
                                            @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <!-- text input -->
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.UserId)<span class="text-red">*</span>
                                            @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control", @placeholder = "UserId" } })
                                            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <!-- text input -->
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Password)<span class="text-red">*</span>
                                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Password", @type = "password" } })
                                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Role)<span class="text-red">*</span>

                                            @Html.DropDownListFor(model => model.Role, (SelectList)ViewBag.ForRole, "Select a role", new { @Class = "form-control", @Id = "ddlRole" })

                                            @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Email)<span class="text-red">*</span>
                                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email" } })
                                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Phone)<span class="text-red">*</span>
                                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control onlynumber", @placeholder = "Phone number" } })
                                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Address)<span class="text-red">*</span>
                                            @Html.TextAreaFor(model => model.Address, new { @class = "form-control", @placeholder = "Enter full address" })
                                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox">
                                                @*  <input class="custom-control-input" type="checkbox" id="cbx_active" value="option1">*@
                                                @Html.CheckBoxFor(model => model.IsActive, new { @class = "custom-control-input" })
                                                @*<label for="cbx_active" class="custom-control-label">Is Active</label>*@
                                                @Html.LabelFor(model => model.IsActive, new { @class = "custom-control-label" })
                                            </div>
                                        </div>
                                    </div>



                                </div>

                                <button onclick="Reset()" type="reset" class="btn btn-secondary text-left">Reset</button>
                                <button type="submit" form="Add" class="btn btn-primary btn-left">Submit</button>
                            </div>
                        </div>

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
                <!-- general form elements disabled -->
                <!-- /.card -->
            }
        </div>

    </section>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        if ('@TempData["SuccessFlag"]' == "1") {
            toastr.success('@TempData["Msg"]');
        }
        else if ('@TempData["SuccessFlag"]' == "0") {
            toastr.error('@TempData["Msg"]');
        }
    });
</script>


<script></script>

FMS/Views/User/List.cshtml
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">User list </h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/Home/Index">Administrator</a></li>
                        <li class="breadcrumb-item active">User list</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-12">

                    <!-- general form elements disabled -->
                    <div class="card card-warning">

                        <!-- /.card-header -->
                        <div class="card-body">
                            @*  <button onclick="Add();" type="button" class="btn  bg-gradient-primary"><i class="fas fa-plus"></i>Add Employe</button>*@
                            @*// @Html.ActionLink("Add Employee", "Add", new { @class = "btn  bg-gradient-primary" })*@
                            @Html.ActionLink("Add User", "Add", "User",
                            new { @class = "btn  bg-gradient-primary" })
                            <div class="clearfix"></div><br />
                            <div id="tblUser">

                            </div>
                        </div>

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
                <!-- general form elements disabled -->
                <!-- /.card -->
            </div>

        </div>

    </section>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        if ('@TempData["SuccessFlag"]' == "1") {
            toastr.success('@TempData["Msg"]');
        }
        else if ('@TempData["SuccessFlag"]' == "0") {
            toastr.error('@TempData["Msg"]');
        }
    });
</script>


<script >
    $(function () {
        LoadUser(0);
    });

    function LoadUser(id) {

        var requestData = {
            id: id
        };
        $.ajax({
            url: '/User/LoadUser',
            type: 'POST',
            data: JSON.stringify(requestData),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            async: true,
            processData: true,
            cache: false,
            error: function (xhr) {
                alert('Error: ' + xhr.statusText);
            },
            success: function (result) {

                $('#tblUser').html("");
                var tblHead = '<table class="table table-bordered table-striped table-responsive-lg" id="example1" cellspacing="0" cellpadding="4" align="Center" style="color:#333333;border-collapse:collapse;"><thead><tr style = "color:White;background-color:#1C5E55;font-weight:bold;" ><th scope="col">Full Name</th><th scope="col">UserId</th><th scope="col">Phone</th><th scope="col">Email</th><th scope="col">Address</th><th scope="col">Role</th><th scope="col">Status</th><th scope="col">Action</th></tr ></thead><tbody>';
                //alert(tblHead);
                var tbody = ""
                for (var i = 0; i < result.length; i++) {
                    var status = null;
                    if (result[i].IsActive == 0) {
                        status = "Inactive"
                    }
                    else {
                        status = "Active"
                    }
                   
                    //  tbody = tbody + '<tbody><tr><td align="left" id=id_' + result[i].roleTitle + '>' + result[i].roleTitle + '</td><td id=id_' + result[i].Permissions + '>' + result[i].Permissions + '</td><td class="td-actions text-center"><a href="#" class="" id="btnCreateRole" onclick="EditRole(\'' + result[i].roleID + '\');"><i class="far fa-edit text-warning"></i> </a>&nbsp;<a href="#" class="" id="btnCreateRole" onclick="DeleteRole(\'' + result[i].roleID + '\')"><i class="fas fa-times text-danger"></i> </a></td></tr>';
                    tbody = tbody + '<tr style="background-color:White;"><td>' + result[i].FullName + ' </td ><td>' + result[i].UserId + '</td><td>' + result[i].Phone + '</td><td>' + result[i].Email + '</td><td>' + result[i].Address + '</td><td>' + result[i].RoleName + '</td><td>' + status + '</td><td><a href="#" onclick="Delete(' + result[i].Id + ')"><i class="far fa-trash-alt"></i></i></a >&nbsp;&nbsp;<a href="#" onclick="Edit(' + result[i].Id + ');"><i class="fa fa-fw fa-edit" ></i></a ></td></tr >'
                }
                $('#tblUser').html(tblHead + tbody + '</tbody></table>');
                $("#example1").DataTable();
            },
        });
    }

    function Edit(id) {
        window.location.href = '/User/Add?id=' + id + '';
    }

    function Delete(userid) {

        bootbox.confirm("Are you sure you want to delete this user?", function (confirm) {
            if (confirm == true) {
                window.location.href = '/User/Delete?userid=' + userid + '';
                // LoadEmployee(0);
            }


        })
    }
</script>